<?php ?>
     
<h1 class="titulo_pagina">SINAES </h1>

<h3>Sistema Nacional de Avaliação da Educação Superior</h3>
<p>O Sistema Nacional de Avaliação da Educação Superior (Sinaes) analisa as instituições, os cursos e o desempenho dos estudantes. O processo de avaliação leva em consideração aspectos como ensino, pesquisa, extensão, responsabilidade social, gestão da instituição e corpo docente. O Sinaes reúne informações do Exame Nacional de Desempenho de Estudantes (Enade) e das avaliações institucionais e dos cursos. As informações obtidas são utilizadas para orientação institucional de estabelecimentos de ensino superior e para embasar políticas públicas. Os dados também são úteis para a sociedade, especialmente aos estudantes, como referência quanto às condições de cursos e instituições.</p>
<p>Os processos avaliativos do Sinaes são coordenados e supervisio­nados pela Comissão Nacional de Avaliação da Educação Superior (Conaes). A operacionalização é de responsabilidade do Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira (Inep).
<em>Fonte: [<a href='http://portal.mec.gov.br/index.php/?id=12303&option=com_content' target='_blank'>MEC</a>] < Acesso em 19/07/2014> </em>
</p>
<p>Criado pela Lei n° 10.861, de 14 de abril de 2004, o Sistema Nacional de Avaliação da Educação Superior (Sinaes) é formado por três componentes principais: a avaliação das instituições, dos cursos e do desempenho dos estudantes. O Sinaes avalia todos os aspectos que giram em torno desses três eixos: o ensino, a pesquisa, a extensão, a responsabilidade social, o desempenho dos alunos, a gestão da instituição, o corpo docente, as instalações e vários outros aspectos.</p>
<p>Ele possui uma série de instrumentos complementares: auto-avaliação, avaliação externa, Enade, Avaliação dos cursos de graduação e instrumentos de informação (censo e cadastro). Os resultados das avaliações possibilitam traçar um panorama da qualidade dos cursos e instituições de educação superior no País. Os processos avaliativos são coordenados e supervisionados pela Comissão Nacional de Avaliação da Educação Superior (Conaes). A operacionalização é de responsabilidade do Inep.</p>
<p>As informações obtidas com o Sinaes são utilizadas pelas IES, para orientação da sua eficácia institucional e efetividade acadêmica e social; pelos órgãos governamentais para orientar políticas públicas e pelos estudantes, pais de alunos, instituições acadêmicas e público em geral, para orientar suas decisões quanto à realidade dos cursos e das instituições.
<em>Fonte: [<a href='http://portal.inep.gov.br/superior-sinaes' target='_blank'>INEP</a>] < Acesso em 19/07/2014></em>
</p>